### ISSUE TITLE
Haiken posts a public report toot with an allowed hashtag for silenced user's toot.

### ISSUE THREAD

**Issue by Nanashia** [aji-su/haiken#1]
https://github.com/aji-su/haiken/blob/5e05d50b8ac93df1d140c8c76725d2026fcec791/haiken.go#L120
**Problem:**
Currently, Haiken posts a report toot with allowed hashtag if source toots has that as well. The visibility of report toots also have the same visibility as well as source. In mastodon, silenced user is hidden from public timelines including hashtag timelines even if the toots visibility is public. 

These behavior causes the problem; when the user who is silenced by the server posts a toot that has a sing, Haiken posts a report for that users content with public visiblity. It looks Haiken seeing inexistsing toots in hashtag timeline and so awkward. In addition, since silence is important feature in mastodon's moderation system, silenced user's content should never posted in public timeline. 

**Solution:**
Stop posting report toots for silenced user in public visivility or with allowed hashtags.

**Comment by Nanashia** [comment]
Mastodon's REST API does not provide if accounts is suspended nor silenced, a few of work may be needed.
I think I can propose a pull request.

**Comment by aji-su** [comment]
Thank you for reporting. There had been other problems with hashtags, so I removed the feature in 2af45b034575b4043db9db0d793f6c6573849695
